# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1223ff51834b5c2ac8a2b78a76f20107"
name = "Checkout Customizer"
handle = "vs-checkout-customizer"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
scopes = "write_checkouts, write_orders, write_products, write_customers"

[auth]
redirect_urls = ["https://example.com/api/auth"]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
