# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-04"

[[extensions]]
type = "ui_extension"
name = "test-block"
handle = "test-block"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview
[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = false
block_progress = true
api_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields
[[extensions.metafields]]
namespace = "vs259"
key = "title"
[[extensions.metafields]]
namespace = "vs259"
key = "description"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition
[extensions.settings]
[[extensions.settings.fields]]
key = "product_id"
type = "single_line_text_field"
name = "Product ID"
description = "Enter the product ID for which the banner must display"

[[extensions.settings.fields]]
key = "banner_message"
type = "multi_line_text_field"
name = "Banner Message"
description = "Enter a custom message for the banner"

[[extensions.settings.fields]]
key = "banner_message_info"
type = "multi_line_text_field"
name = "Banner Info"
description = "Enter a custom message for the banner info"